# tasks file for collectd
---
- name: install dependencies
  apt:
    name: "{{ collectd_dependencies }}"
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  tags:
    - configuration
    - collectd
    - collectd-dependencies

- name: install additional
  apt:
    name: "{{ collectd_install }}"
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  notify: restart collectd
  tags:
    - configuration
    - collectd
    - collectd-additional

- name: plugins | enable and configure
  template:
    src: "etc/collectd/collectd.conf.d/{{ item }}.conf.j2"
    dest: "/etc/collectd/collectd.conf.d/{{ item }}.conf"
  with_items: "{{ collectd_plugins_present }}"
  notify: restart collectd
  tags:
    - configuration
    - collectd
    - collectd-plugins
    - collectd-plugins-enable
    - collectd-plugins-configure

- name: plugins | disable (remove configuration file)
  file:
    dest: "/etc/collectd/collectd.conf.d/{{ item }}.conf"
    state: absent
  with_items: "{{ collectd_plugins_absent }}"
  notify: restart collectd
  tags:
    - configuration
    - collectd
    - collectd-plugins
    - collectd-plugins-disable
    - collectd-plugins-remove-configuration-file

- name: plugins | disable (remove LoadPlugin)
  lineinfile:
    path: "{{ collectd_configuration_file }}"
    state: absent
    regexp: "^LoadPlugin {{ item }}"
  with_items: "{{ collectd_plugins_absent }}"
  notify: restart collectd
  tags:
    - configuration
    - collectd
    - collectd-plugins
    - collectd-plugins-disable
    - collectd-plugins-remove-load-plugin

- name: plugins | disable (remove configuration block)
  blockinfile:
    path: "{{ collectd_configuration_file }}"
    state: absent
    marker: "{mark}"
    marker_begin: "<Plugin {{ item }}>"
    marker_end: '</Plugin>'
  with_items: "{{ collectd_plugins_absent }}"
  notify: restart collectd
  tags:
    - configuration
    - collectd
    - collectd-plugins
    - collectd-plugins-disable
    - collectd-plugins-remove-configuration-block

- name: start and enable service
  service:
    name: collectd
    state: "{{ service_default_state | default('started') }}"
    enabled: "{{ service_default_enabled | default(true) | bool }}"
  tags:
    - collectd-start-enable-service
