# tasks file
---
- name: install dependencies
  tags:
    - configuration
    - collectd
    - collectd-dependencies
  block:
    # See: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=863199
    - name: ensure man directory
      ansible.builtin.file:
        path: /usr/share/man/man1
        state: directory
        recurse: true
      when:
        - ansible_distribution == 'Ubuntu'
        - ansible_distribution_major_version is version('18', '>=')

    - name: install dependencies
      ansible.builtin.apt:
        name: "{{ collectd_dependencies }}"
        state: "{{ apt_install_state | default('latest') }}"
        update_cache: true
        cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"

- name: install additional
  ansible.builtin.apt:
    name: "{{ collectd_install }}"
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  notify: restart collectd
  tags:
    - configuration
    - collectd
    - collectd-additional

- name: configure
  ansible.builtin.template:
    src: "etc/default/collectd.j2"
    dest: "/etc/default/collectd"
    mode: 0644
  notify: restart collectd
  tags:
    - configuration
    - collectd
    - collectd-configure

- name: plugins | enable and configure
  ansible.builtin.template:
    src: "etc/collectd/collectd.conf.d/{{ item }}.conf.j2"
    dest: "/etc/collectd/collectd.conf.d/{{ item }}.conf"
    mode: 0644
  with_items: "{{ collectd_plugins_present }}"
  notify: restart collectd
  tags:
    - configuration
    - collectd
    - collectd-plugins
    - collectd-plugins-enable
    - collectd-plugins-configure

- name: plugins | disable (remove configuration file)
  ansible.builtin.file:
    dest: "/etc/collectd/collectd.conf.d/{{ item }}.conf"
    state: absent
  with_items: "{{ collectd_plugins_absent }}"
  notify: restart collectd
  tags:
    - configuration
    - collectd
    - collectd-plugins
    - collectd-plugins-disable
    - collectd-plugins-remove-configuration-file

- name: plugins | disable (remove LoadPlugin)
  ansible.builtin.lineinfile:
    path: "{{ collectd_configuration_file }}"
    state: absent
    regexp: "^LoadPlugin {{ item }}"
  with_items: "{{ collectd_plugins_absent }}"
  notify: restart collectd
  tags:
    - configuration
    - collectd
    - collectd-plugins
    - collectd-plugins-disable
    - collectd-plugins-remove-load-plugin

- name: plugins | disable (remove configuration block)
  ansible.builtin.blockinfile:
    path: "{{ collectd_configuration_file }}"
    state: absent
    marker: "{mark}"
    marker_begin: "<Plugin {{ item }}>"
    marker_end: '</Plugin>'
  with_items: "{{ collectd_plugins_absent }}"
  notify: restart collectd
  tags:
    - configuration
    - collectd
    - collectd-plugins
    - collectd-plugins-disable
    - collectd-plugins-remove-configuration-block

- name: start and enable service
  ansible.builtin.service:
    name: collectd
    state: "{{ service_default_state | default('started') }}"
    enabled: "{{ service_default_enabled | default(true) | bool }}"
  tags:
    - collectd-start-enable-service
